from django.contrib import admin
from .models import *

admin.site.register(CustomUser)
admin.site.register(StudentProfile)
admin.site.register(TeacherProfile)
admin.site.register(Course)
admin.site.register(Menu)
admin.site.register(Banner)
admin.site.register(Lesson)
admin.site.register(LessonFile)
admin.site.register(LessonComment)
admin.site.register(Exercise)
admin.site.register(ExerciseSubmission)
admin.site.register(Quiz)
admin.site.register(Question)
admin.site.register(Choice)
admin.site.register(QuizAttempt)
admin.site.register(StudentAnswer)
admin.site.register(LearningProgress)
admin.site.register(GradeSummary)
admin.site.register(VisitStat)
admin.site.register(ChatbotLog)
admin.site.register(ExamAlert)
admin.site.register(SystemSetting)
admin.site.register(Announcement)