# Generated by Django 6.0.3 on 2026-03-19 15:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "banner_name",
                    models.CharField(max_length=255, verbose_name="ชื่อแบนเนอร์"),
                ),
                ("banner_title", models.CharField(max_length=255, verbose_name="หัวข้อ")),
                (
                    "banner_description",
                    models.TextField(blank=True, verbose_name="รายละเอียด"),
                ),
                (
                    "banner_image",
                    models.ImageField(upload_to="banners/", verbose_name="รูปภาพ"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ข้อความปุ่ม"
                    ),
                ),
                ("button_link", models.URLField(blank=True, verbose_name="ลิงก์ปลายทาง")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ลำดับการแสดง"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่เริ่มแสดง"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่สิ้นสุด"),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
            ],
            options={
                "verbose_name": "แบนเนอร์",
                "verbose_name_plural": "แบนเนอร์",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "course_code",
                    models.CharField(max_length=50, unique=True, verbose_name="รหัสวิชา"),
                ),
                ("course_name", models.CharField(max_length=255, verbose_name="ชื่อวิชา")),
                (
                    "course_description",
                    models.TextField(blank=True, verbose_name="คำอธิบายรายวิชา"),
                ),
                (
                    "course_objective",
                    models.TextField(blank=True, verbose_name="วัตถุประสงค์รายวิชา"),
                ),
                (
                    "total_hours",
                    models.PositiveIntegerField(default=0, verbose_name="จำนวนชั่วโมง"),
                ),
                (
                    "credit_unit",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=4, verbose_name="หน่วยกิต"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="รูปปกวิชา",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายวิชา",
                "verbose_name_plural": "รายวิชา",
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("question_no", models.PositiveIntegerField(verbose_name="เลขข้อ")),
                ("question_text", models.TextField(verbose_name="คำถาม")),
                (
                    "question_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/",
                        verbose_name="รูปภาพประกอบ",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "ปรนัย"),
                            ("true_false", "ถูกผิด"),
                            ("short_answer", "คำตอบสั้น"),
                        ],
                        default="multiple_choice",
                        max_length=30,
                        verbose_name="ประเภทคำถาม",
                    ),
                ),
                (
                    "question_score",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=6, verbose_name="คะแนน"
                    ),
                ),
                (
                    "difficulty_level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="ระดับความยาก",
                    ),
                ),
                (
                    "explanation_text",
                    models.TextField(blank=True, verbose_name="คำอธิบายเฉลย"),
                ),
            ],
            options={
                "verbose_name": "ข้อคำถาม",
                "verbose_name_plural": "ข้อคำถาม",
                "ordering": ["quiz", "question_no"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="DB Learning Online",
                        max_length=255,
                        verbose_name="ชื่อเว็บไซต์",
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="โลโก้",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ข้อความส่วนท้าย"
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(blank=True, max_length=20, verbose_name="สีธีม"),
                ),
                (
                    "chatbot_enabled",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน Chatbot"),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(default=True, verbose_name="เปิดสมัครสมาชิก"),
                ),
                (
                    "quiz_attempt_limit",
                    models.PositiveIntegerField(
                        default=1, verbose_name="จำนวนครั้งที่อนุญาตให้สอบ"
                    ),
                ),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=30, verbose_name="เวลาหมด Session (นาที)"
                    ),
                ),
                (
                    "copyright_year",
                    models.PositiveIntegerField(default=2026, verbose_name="ปีลิขสิทธิ์"),
                ),
            ],
            options={
                "verbose_name": "การตั้งค่าระบบ",
                "verbose_name_plural": "การตั้งค่าระบบ",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=20, verbose_name="คำนำหน้า"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="ชื่อที่แสดง"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="เบอร์โทร"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="รูปโปรไฟล์",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "นักเรียน"),
                            ("teacher", "ครู"),
                            ("admin", "ผู้ดูแลระบบ"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="บทบาทผู้ใช้",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ใช้งาน"),
                            ("inactive", "ไม่ใช้งาน"),
                            ("suspended", "ระงับการใช้งาน"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="สถานะการใช้งาน",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="หัวข้อ")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                ("announce_date", models.DateTimeField(verbose_name="วันที่ประกาศ")),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่หมดอายุ"
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ประกาศ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประกาศ",
                "verbose_name_plural": "ประกาศ",
                "ordering": ["-announce_date"],
            },
        ),
        migrations.CreateModel(
            name="ChatbotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Session ID"
                    ),
                ),
                ("question_text", models.TextField(verbose_name="คำถาม")),
                ("answer_text", models.TextField(verbose_name="คำตอบ")),
                (
                    "chat_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่เวลา"),
                ),
                (
                    "page_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="หน้าที่ถาม"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ประเภทคำถาม"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatbot_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติ Chatbot",
                "verbose_name_plural": "ประวัติ Chatbot",
                "ordering": ["-chat_time"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("lesson_no", models.PositiveIntegerField(verbose_name="ลำดับบทเรียน")),
                (
                    "lesson_title",
                    models.CharField(max_length=255, verbose_name="ชื่อบทเรียน"),
                ),
                (
                    "lesson_description",
                    models.TextField(blank=True, verbose_name="คำอธิบายบทเรียน"),
                ),
                (
                    "lesson_content",
                    models.TextField(blank=True, verbose_name="เนื้อหาหลัก"),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lessons/thumbnails/",
                        verbose_name="รูปปก",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="ลิงก์วิดีโอ")),
                (
                    "attachment_info",
                    models.TextField(blank=True, verbose_name="ข้อมูลไฟล์เอกสารประกอบ"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ลำดับการแสดง"),
                ),
                (
                    "study_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ระยะเวลาเรียน (นาที)"
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="appdblearn.course",
                        verbose_name="รายวิชา",
                    ),
                ),
            ],
            options={
                "verbose_name": "บทเรียน",
                "verbose_name_plural": "บทเรียน",
                "ordering": ["course", "lesson_no"],
                "unique_together": {("course", "lesson_no")},
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "exercise_title",
                    models.CharField(max_length=255, verbose_name="ชื่อแบบฝึกหัด"),
                ),
                ("instruction", models.TextField(blank=True, verbose_name="คำชี้แจง")),
                (
                    "full_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนเต็ม",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันเริ่ม"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันสิ้นสุด"),
                ),
                (
                    "attachment_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exercise_attachments/",
                        verbose_name="ไฟล์แนบ",
                    ),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="appdblearn.course",
                        verbose_name="รายวิชา",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="appdblearn.lesson",
                        verbose_name="บทเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "แบบฝึกหัด",
                "verbose_name_plural": "แบบฝึกหัด",
            },
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("comment_text", models.TextField(verbose_name="ข้อความคอมเมนต์")),
                (
                    "comment_status",
                    models.CharField(
                        choices=[
                            ("pending", "รออนุมัติ"),
                            ("approved", "อนุมัติ"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะคอมเมนต์",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="appdblearn.lesson",
                        verbose_name="บทเรียน",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="appdblearn.lessoncomment",
                        verbose_name="คอมเมนต์แม่",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้แสดงความคิดเห็น",
                    ),
                ),
            ],
            options={
                "verbose_name": "คอมเมนต์บทเรียน",
                "verbose_name_plural": "คอมเมนต์บทเรียน",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="ชื่อไฟล์")),
                (
                    "file_type",
                    models.CharField(blank=True, max_length=50, verbose_name="ชนิดไฟล์"),
                ),
                (
                    "file",
                    models.FileField(upload_to="lesson_files/", verbose_name="ไฟล์"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="ขนาดไฟล์ (bytes)"
                    ),
                ),
                (
                    "file_description",
                    models.TextField(blank=True, verbose_name="คำอธิบายไฟล์"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="appdblearn.lesson",
                        verbose_name="บทเรียน",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_lesson_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้อัปโหลด",
                    ),
                ),
            ],
            options={
                "verbose_name": "ไฟล์บทเรียน",
                "verbose_name_plural": "ไฟล์บทเรียน",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("menu_name", models.CharField(max_length=100, verbose_name="ชื่อเมนู")),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("main", "เมนูหลัก"), ("sub", "เมนูย่อย")],
                        default="main",
                        max_length=10,
                        verbose_name="ประเภทเมนู",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ลำดับการแสดงผล"
                    ),
                ),
                (
                    "menu_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="path/url"
                    ),
                ),
                (
                    "menu_icon",
                    models.CharField(blank=True, max_length=100, verbose_name="icon"),
                ),
                (
                    "permission_role",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="สิทธิ์การเข้าถึง"
                    ),
                ),
                (
                    "menu_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="สถานะการใช้งาน",
                    ),
                ),
                (
                    "parent_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="appdblearn.menu",
                        verbose_name="เมนูแม่",
                    ),
                ),
            ],
            options={
                "verbose_name": "เมนู",
                "verbose_name_plural": "เมนู",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("choice_label", models.CharField(max_length=5, verbose_name="ตัวเลือก")),
                ("choice_text", models.TextField(verbose_name="ข้อความตัวเลือก")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="ถูกต้อง"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ลำดับตัวเลือก"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="appdblearn.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตัวเลือกคำตอบ",
                "verbose_name_plural": "ตัวเลือกคำตอบ",
                "ordering": ["question", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "quiz_title",
                    models.CharField(max_length=255, verbose_name="ชื่อแบบทดสอบ"),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("pretest", "ก่อนเรียน"),
                            ("posttest", "หลังเรียน"),
                            ("practice", "แบบฝึกทบทวน"),
                        ],
                        default="pretest",
                        max_length=20,
                        verbose_name="ประเภทแบบทดสอบ",
                    ),
                ),
                (
                    "quiz_description",
                    models.TextField(blank=True, verbose_name="คำอธิบาย"),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(default=0, verbose_name="จำนวนข้อ"),
                ),
                (
                    "full_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนเต็ม",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=0, verbose_name="เวลาที่กำหนด (นาที)"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(default=False, verbose_name="สุ่มข้อสอบ"),
                ),
                (
                    "shuffle_choices",
                    models.BooleanField(default=False, verbose_name="สุ่มตัวเลือก"),
                ),
                (
                    "show_result_immediately",
                    models.BooleanField(default=False, verbose_name="แสดงผลคะแนนทันที"),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "ฉบับร่าง"),
                            ("published", "เผยแพร่"),
                            ("hidden", "ซ่อน"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะเผยแพร่",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="appdblearn.course",
                        verbose_name="รายวิชา",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="appdblearn.lesson",
                        verbose_name="บทเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "แบบทดสอบ",
                "verbose_name_plural": "แบบทดสอบ",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="appdblearn.quiz",
                verbose_name="แบบทดสอบ",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                ("start_time", models.DateTimeField(verbose_name="เวลาเริ่ม")),
                (
                    "submit_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="เวลาส่ง"),
                ),
                (
                    "time_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="เวลาที่ใช้ (วินาที)"
                    ),
                ),
                (
                    "score_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนที่ได้",
                    ),
                ),
                (
                    "score_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="เปอร์เซ็นต์คะแนน",
                    ),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[
                            ("in_progress", "กำลังทำ"),
                            ("submitted", "ส่งแล้ว"),
                            ("timeout", "หมดเวลา"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="สถานะการทำข้อสอบ",
                    ),
                ),
                (
                    "answered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="จำนวนข้อที่ตอบแล้ว"
                    ),
                ),
                (
                    "unanswered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="จำนวนข้อที่ยังไม่ตอบ"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="appdblearn.quiz",
                        verbose_name="แบบทดสอบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "การทำแบบทดสอบ",
                "verbose_name_plural": "การทำแบบทดสอบ",
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="ตอบถูก"),
                ),
                (
                    "answer_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนที่ได้",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="เวลาที่ตอบ"
                    ),
                ),
                (
                    "answer_order",
                    models.PositiveIntegerField(default=0, verbose_name="ลำดับการตอบ"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="appdblearn.quizattempt",
                        verbose_name="การทำแบบทดสอบ",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_answers",
                        to="appdblearn.choice",
                        verbose_name="ตัวเลือกที่เลือก",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="appdblearn.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำตอบของนักเรียน",
                "verbose_name_plural": "คำตอบของนักเรียน",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "student_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="รหัสนักเรียน"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=50, verbose_name="ระดับชั้น"),
                ),
                (
                    "class_room",
                    models.CharField(blank=True, max_length=50, verbose_name="ห้อง"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="สาขาวิชา"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ปีการศึกษา"
                    ),
                ),
                (
                    "student_number",
                    models.CharField(blank=True, max_length=20, verbose_name="เลขที่"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="วันเกิด"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ชาย"), ("female", "หญิง"), ("other", "อื่น ๆ")],
                        max_length=20,
                        verbose_name="เพศ",
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เบอร์ผู้ปกครอง/ฉุกเฉิน"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลนักเรียน",
                "verbose_name_plural": "ข้อมูลนักเรียน",
            },
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="appdblearn.studentprofile",
                verbose_name="นักเรียน",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="ข้อความคำตอบ"),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exercise_submissions/",
                        verbose_name="ไฟล์ที่ส่ง",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่ส่ง"),
                ),
                (
                    "score_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนที่ได้",
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(blank=True, verbose_name="ความเห็นจากครู"),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "รอตรวจ"),
                            ("checked", "ตรวจแล้ว"),
                            ("returned", "ส่งกลับ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะการตรวจ",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="appdblearn.exercise",
                        verbose_name="แบบฝึกหัด",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_submissions",
                        to="appdblearn.studentprofile",
                        verbose_name="นักเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การส่งแบบฝึกหัด",
                "verbose_name_plural": "การส่งแบบฝึกหัด",
            },
        ),
        migrations.CreateModel(
            name="ExamAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=100, verbose_name="ประเภทความผิดปกติ"),
                ),
                (
                    "alert_detail",
                    models.TextField(blank=True, verbose_name="รายละเอียดเหตุการณ์"),
                ),
                (
                    "alert_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาเกิดเหตุ"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "ต่ำ"),
                            ("medium", "ปานกลาง"),
                            ("high", "สูง"),
                            ("critical", "วิกฤต"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="ระดับความเสี่ยง",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("new", "ใหม่"),
                            ("reviewing", "กำลังตรวจสอบ"),
                            ("resolved", "ตรวจสอบแล้ว"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="สถานะตรวจสอบ",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="หมายเหตุจากแอดมิน"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="appdblearn.quiz",
                        verbose_name="แบบทดสอบ",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="appdblearn.quizattempt",
                        verbose_name="การทำข้อสอบ",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_alerts",
                        to="appdblearn.studentprofile",
                        verbose_name="นักเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "แจ้งเตือนทุจริต",
                "verbose_name_plural": "แจ้งเตือนทุจริต",
                "ordering": ["-alert_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=255, verbose_name="ชื่อ-นามสกุล"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="ตำแหน่ง"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="แผนกวิชา"
                    ),
                ),
                (
                    "teacher_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="รูปภาพ",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="ช่องทางติดต่อ"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "line_id",
                    models.CharField(blank=True, max_length=100, verbose_name="Line"),
                ),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email ติดต่อ"
                    ),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="เว็บไซต์")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลครู",
                "verbose_name_plural": "ข้อมูลครู",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="main_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="appdblearn.teacherprofile",
                verbose_name="ผู้สอนหลัก",
            ),
        ),
        migrations.CreateModel(
            name="VisitStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="รหัสผู้เยี่ยมชม"
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่เวลาเข้าชม"
                    ),
                ),
                ("page_url", models.CharField(max_length=255, verbose_name="หน้าเว็บ")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "browser_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Browser"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, max_length=100, verbose_name="อุปกรณ์"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Session ID"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ระยะเวลา (วินาที)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถิติการเข้าชม",
                "verbose_name_plural": "สถิติการเข้าชม",
            },
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("quiz", "question_no")},
        ),
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "lesson_status",
                    models.CharField(
                        choices=[
                            ("not_started", "ยังไม่เรียน"),
                            ("in_progress", "กำลังเรียน"),
                            ("completed", "เรียนจบ"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="สถานะบทเรียน",
                    ),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="เปอร์เซ็นต์ความคืบหน้า",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่เริ่มเรียน"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่เรียนจบ"
                    ),
                ),
                (
                    "study_time_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="เวลาเรียนสะสม (วินาที)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to="appdblearn.course",
                        verbose_name="รายวิชา",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to="appdblearn.lesson",
                        verbose_name="บทเรียน",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to="appdblearn.studentprofile",
                        verbose_name="นักเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ความคืบหน้าการเรียน",
                "verbose_name_plural": "ความคืบหน้าการเรียน",
                "unique_together": {("student", "course", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="GradeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
                (
                    "pretest_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนก่อนเรียน",
                    ),
                ),
                (
                    "posttest_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนหลังเรียน",
                    ),
                ),
                (
                    "exercise_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนแบบฝึกหัด",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="คะแนนรวม",
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="ระดับผลการเรียน"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_summaries",
                        to="appdblearn.course",
                        verbose_name="รายวิชา",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_summaries",
                        to="appdblearn.studentprofile",
                        verbose_name="นักเรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "สรุปผลคะแนน",
                "verbose_name_plural": "สรุปผลคะแนน",
                "unique_together": {("student", "course")},
            },
        ),
    ]
